test v1

diff --git a/.github/workflows/check_scripts.yml b/.github/workflows/check_scripts.yml
--- a/.github/workflows/check_scripts.yml
+++ b/.github/workflows/check_scripts.yml
@@ -75,8 +75,8 @@ jobs:
       fail-fast: false
       max-parallel: 20
       matrix:
-        java_version: [ 8 ]
-#        java_version: [ 8, 11, 13, 15, 17, 18, 19 ]
+#        java_version: [ 8 ]
+        java_version: [ 8, 11, 13, 15, 17, 18, 19 ]
         os: [ windows-latest ]
     steps:
       # set java
@@ -113,14 +113,14 @@ jobs:
         id: build-iotdb
         shell: pwsh
         run: |
-          C:\msys64\usr\bin\wget.exe -O${{ github.workspace }}/apache-iotdb-1.0.1-SNAPSHOT-all-bin-master-e68f560463.zip  https://github.com/xiaoyekanren/iotdb-daily-build/releases/download/2022-12-12-java8-apache-iotdb/apache-iotdb-1.0.1-SNAPSHOT-all-bin-master-e68f560463.zip
-          7z x apache-iotdb-1.0.1-SNAPSHOT-all-bin-master-e68f560463.zip
-          cd apache-iotdb-1.0.1-SNAPSHOT-all-bin
+          cd ${{ github.workspace }}/iotdb-src
+          mvn clean package -DskipTests -am -pl distribution
+          mv ${{ github.workspace }}/iotdb-src/distribution/target/apache-iotdb-${{ needs.check-commit.outputs.version }}-all-bin/apache-iotdb-${{ needs.check-commit.outputs.version }}-all-bin ${{ github.workspace }}/iotdb-bin
+          cd ${{ github.workspace }}/iotdb-bin
           echo "::set-output name=iotdb_home::$(pwd)"
-#          cd ${{ github.workspace }}/iotdb-src
-#          mvn clean package -DskipTests -am -pl distribution
-#          mv ${{ github.workspace }}/iotdb-src/distribution/target/apache-iotdb-${{ needs.check-commit.outputs.version }}-all-bin/apache-iotdb-${{ needs.check-commit.outputs.version }}-all-bin ${{ github.workspace }}/iotdb-bin
-#          cd ${{ github.workspace }}/iotdb-bin
+#          C:\msys64\usr\bin\wget.exe -O${{ github.workspace }}/apache-iotdb-1.0.1-SNAPSHOT-all-bin-master-e68f560463.zip  https://github.com/xiaoyekanren/iotdb-daily-build/releases/download/2022-12-12-java8-apache-iotdb/apache-iotdb-1.0.1-SNAPSHOT-all-bin-master-e68f560463.zip
+#          7z x apache-iotdb-1.0.1-SNAPSHOT-all-bin-master-e68f560463.zip
+#          cd apache-iotdb-1.0.1-SNAPSHOT-all-bin
 #          echo "::set-output name=iotdb_home::$(pwd)"
       - name: check para.
         if: ${{ matrix.os == 'windows-latest' }}
@@ -196,92 +196,92 @@ jobs:
           cd ${{ github.workspace }}/iotdb-daily-build/check_scripts
           step_6_check_stop_confignode.bat ${{ steps.build-iotdb.outputs.iotdb_home }}
 
-#  check-in-linux:
-#    needs: check-commit
-#    runs-on: ${{ matrix.os }}
-#    strategy:
-#      fail-fast: false
-#      max-parallel: 20
-#      matrix:
-#        java_version: [ 8, 11, 13, 15, 17, 18, 19 ]
-#        os: [ ubuntu-latest ]
-#    steps:
-#      # set java
-#      - name: Set java ${{ matrix.java_version }}
-#        uses: actions/setup-java@v3
-#        with:
-#          java-version: ${{ matrix.java_version }}
-#          distribution: 'zulu'
-#      # get iotdb
-#      - name: Checkout apache/iotdb
-#        uses: actions/checkout@v2
-#        with:
-#          path: iotdb
-#          repository: 'apache/iotdb'
-#          ref: 'rel/1.0'
-#          fetch-depth: 0
-#      # build iotdb
-#      - name: build iotdb
-#        id: build-iotdb
-#        run: |
-#          cd ${{ github.workspace }}/iotdb
-#          mvn clean package -DskipTests -am -pl distribution
-#          mv ${{ github.workspace }}/iotdb/distribution/target/apache-iotdb-${{ needs.check-commit.outputs.version }}-all-bin/apache-iotdb-${{ needs.check-commit.outputs.version }}-all-bin ${{ github.workspace }}/iotdb-binary
-#      # test
-#      - name: test start on ${{matrix.os}}
-#        if: ${{ matrix.os == 'ubuntu-latest' }}
-#        run: |
-#          cd ${{ github.workspace }}/iotdb-binary
-#          nohup sbin/start-confignode.sh > /dev/null 2>&1 &
-#          cf_pid=$!
-#          echo "confignode pid is ${cf_pid}"
-#          sleep 5
-#          nohup sbin/start-datanode.sh > /dev/null 2>&1 &
-#          df_pid=$!
-#          echo "datanode pid is ${df_pid}"
-#          sleep 60
-#
-#          ps_cf_pid=$(ps -aux | grep $cf_pid | grep -v 'grep --color=auto' | grep -v '[g]rep' | awk '{print $2}')
-#          ps_df_pid=$(ps -aux | grep $df_pid | grep -v 'grep --color=auto' | grep -v '[g]rep' | awk '{print $2}')
-#
-#          if [ "${ps_df_pid}1" == "1" ]; then
-#              echo "Check start-datanode failed. exit.."
-#              echo ------${ps_df_pid}1------
-#              exit 1
-#          else
-#              echo "Check start-datanode Success. "
-#          fi
-#
-#          if [ "${ps_cf_pid}1" == "1" ]; then
-#              echo "Check start-confignode failed. exit.."
-#              echo ------${ps_cf_pid}1------
-#              exit 1
-#          else
-#              echo "Check start-confignode Success. "
-#          fi
-#
-#          sbin/stop-datanode.sh && sleep 5
-#          ps -aux | grep $df_pid | grep -v 'grep --color=auto' | grep -v '[g]rep' | awk '{print $2}'
-#          ps_df_pid=$(ps -aux | grep $df_pid | grep -v 'grep --color=auto' | grep -v '[g]rep' | awk '{print $2}')
-#          if [ "${ps_df_pid}1" == "1" ]; then
-#              echo "Check stop-datanode Success. "
-#          else
-#              echo "Check stop-datanode failed. exit.."
-#              echo ------${ps_df_pid}1------
-#              exit 1
-#          fi
-#
-#          sbin/stop-confignode.sh && sleep 5
-#          ps -aux | grep $cf_pid | grep -v 'grep --color=auto' | grep -v '[g]rep' | awk '{print $2}'
-#          ps_cf_pid=$(ps -aux | grep $cf_pid | grep -v 'grep --color=auto' | grep -v '[g]rep' | awk '{print $2}')
-#          if [ "${ps_cf_pid}1" == "1" ]; then
-#              echo "Check stop-confignode Success. "
-#          else
-#              echo "Check stop-confignode failed. exit.."
-#              echo ------${ps_cf_pid}1------
-#              exit 1
-#          fi
-#
+  check-in-linux:
+    needs: check-commit
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      max-parallel: 20
+      matrix:
+        java_version: [ 8, 11, 13, 15, 17, 18, 19 ]
+        os: [ ubuntu-latest ]
+    steps:
+      # set java
+      - name: Set java ${{ matrix.java_version }}
+        uses: actions/setup-java@v3
+        with:
+          java-version: ${{ matrix.java_version }}
+          distribution: 'zulu'
+      # get iotdb
+      - name: Checkout apache/iotdb
+        uses: actions/checkout@v2
+        with:
+          path: iotdb
+          repository: 'apache/iotdb'
+          ref: 'rel/1.0'
+          fetch-depth: 0
+      # build iotdb
+      - name: build iotdb
+        id: build-iotdb
+        run: |
+          cd ${{ github.workspace }}/iotdb
+          mvn clean package -DskipTests -am -pl distribution
+          mv ${{ github.workspace }}/iotdb/distribution/target/apache-iotdb-${{ needs.check-commit.outputs.version }}-all-bin/apache-iotdb-${{ needs.check-commit.outputs.version }}-all-bin ${{ github.workspace }}/iotdb-binary
+      # test
+      - name: test start on ${{matrix.os}}
+        if: ${{ matrix.os == 'ubuntu-latest' }}
+        run: |
+          cd ${{ github.workspace }}/iotdb-binary
+          nohup sbin/start-confignode.sh > /dev/null 2>&1 &
+          cf_pid=$!
+          echo "confignode pid is ${cf_pid}"
+          sleep 5
+          nohup sbin/start-datanode.sh > /dev/null 2>&1 &
+          df_pid=$!
+          echo "datanode pid is ${df_pid}"
+          sleep 60
+
+          ps_cf_pid=$(ps -aux | grep $cf_pid | grep -v 'grep --color=auto' | grep -v '[g]rep' | awk '{print $2}')
+          ps_df_pid=$(ps -aux | grep $df_pid | grep -v 'grep --color=auto' | grep -v '[g]rep' | awk '{print $2}')
+
+          if [ "${ps_df_pid}1" == "1" ]; then
+              echo "Check start-datanode failed. exit.."
+              echo ------${ps_df_pid}1------
+              exit 1
+          else
+              echo "Check start-datanode Success. "
+          fi
+
+          if [ "${ps_cf_pid}1" == "1" ]; then
+              echo "Check start-confignode failed. exit.."
+              echo ------${ps_cf_pid}1------
+              exit 1
+          else
+              echo "Check start-confignode Success. "
+          fi
+
+          sbin/stop-datanode.sh && sleep 5
+          ps -aux | grep $df_pid | grep -v 'grep --color=auto' | grep -v '[g]rep' | awk '{print $2}'
+          ps_df_pid=$(ps -aux | grep $df_pid | grep -v 'grep --color=auto' | grep -v '[g]rep' | awk '{print $2}')
+          if [ "${ps_df_pid}1" == "1" ]; then
+              echo "Check stop-datanode Success. "
+          else
+              echo "Check stop-datanode failed. exit.."
+              echo ------${ps_df_pid}1------
+              exit 1
+          fi
+
+          sbin/stop-confignode.sh && sleep 5
+          ps -aux | grep $cf_pid | grep -v 'grep --color=auto' | grep -v '[g]rep' | awk '{print $2}'
+          ps_cf_pid=$(ps -aux | grep $cf_pid | grep -v 'grep --color=auto' | grep -v '[g]rep' | awk '{print $2}')
+          if [ "${ps_cf_pid}1" == "1" ]; then
+              echo "Check stop-confignode Success. "
+          else
+              echo "Check stop-confignode failed. exit.."
+              echo ------${ps_cf_pid}1------
+              exit 1
+          fi
+
 #  push-commit-id:
 ##    needs: [ check-in-linux,check-in-windows ]
 #    needs: [ check-in-windows ]
